apiVersion: v1
kind: Secret
metadata:
  name: credit-api-secrets
  namespace: credit-staging
type: Opaque
stringData:
  API_KEY: "change-me"
---
apiVersion: v1
kind: Secret
metadata:
  name: credit-api-secrets
  namespace: credit-prod
type: Opaque
stringData:
  API_KEY: "change-me"
