apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: credit-api
  namespace: credit-staging
spec:
  ingressClassName: nginx
  rules:
    - host: credit-api-staging.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: credit-api
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: credit-api
  namespace: credit-prod
spec:
  ingressClassName: nginx
  rules:
    - host: credit-api.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: credit-api
                port:
                  number: 80
